branch-defaults:
  master:
    environment: MargaritaWeb
    group_suffix: null
global:
  application_name: MargaritaWeb
  branch: null
  default_ec2_keyname: avalenieks
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
